server:
  port: 8093

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  # Para formatear el SQL
    show-sql: true  # Mostrar las consultas SQL en la consola

  logging:
    level:
      org.hibernate.SQL: DEBUG  # Mostrar las consultas SQL
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET}


appDescription: "Category API"
appVersion: "1.0.0"